config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:index, :edit, :show, :update] do
    resources :reviews
    resources :contacts, only: [:new, :create]
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get "professional/register" =>"registrations#professional_register"
    get "user/choose" => "registrations#choose"
  end

  resources :projects do
    # member do
    #   put "like" => "projects#upvote"
    # end
  end

  resources :project_attachments, only: [:edit, :update]

  #root 'projects#index'

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  root 'prehome#index'
  # get '*path' => redirect('/')

  #Additional Pages for sorting out projects and professional
    #Projects
    match 'commercials' => 'projects#commercials', :via => :get
    match 'residentials' => 'projects#residentials', :via => :get
    match 'offices' => 'projects#offices', :via => :get

    #Profile
    match 'professional/architects' => 'profiles#architects', :via => :get
    match 'professional/intdesigner' => 'profiles#interior_designers', :via => :get
    match 'professional/architect-firms' => 'profiles#architect_firms', :via => :get
    match 'professional/intdesigner-firms' => 'profiles#architect_firms', :via => :get
    match 'professional/design-firms' => 'profiles#design_firms', :via => :get
    match 'professional/land-architects' => 'profiles#land_architects', :via => :get
    match 'professional/gen-contractors' => 'profiles#gen_contractors', :via => :get
  
end

app/controllers/prehome_controller.rb
class PrehomeController < ApplicationController
  
  before_action :search

  def index
  	@projects = Project.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
  end

  private

  def search
  	@q = Profile.ransack(params[:q])
    @people = @q.result(distinct: true).order("created_at DESC")
    render :partial => 'something/index'
  end

end

app/helpers/prehome_helper.rb
module PrehomeHelper
end

app/views/prehome/index.html.erb
	    <section id="hero-area">
	        <div class="container">
	            <div class="row">
	                <div class="col-md-6">
	                    <div class="content-block">
	                        <h1 class="wow fadeInDown">Seembu</h1>
	                        <p class="wow fadeInDown hero-area-subtitle" data-wow-delay="0.3s"> Seek Inspiration | Meet Professionals | Build Dreams</p>
                             </br></br>
	                        <div class="wow fadeInDown" data-wow-delay="0.3s">
	                        	<%= link_to 'Register Now', user_choose_path, class: "btn btn-default btn-home" %>
	                        </div>
	                    </div>
	                </div>
	            </div><!-- .row close -->
	        </div><!-- .container close -->
	    </section><!-- header close -->



        <!-- 
        About start
        ==================== -->
        <section id="about" class="section">
            <div class="container wow fadeInLeft">
                <div class="heading wow fadeInUp">
                    <h2 class="text-center">About us</h2>
                </div>
                <div class="sub-heading text-center about-us-subheading">
                    <h3>We are a company that bridges professional builders and potential clients who are aiming to build a dream project.</h3>
                </div>
                <div class="block text-center">
                    <p> We will help you explore collections of professional's inspiring ideas that suit your preference, find reliable building professionals who are qualified to execute your dream building project, and connect with building professionals in order to collaborate for implementation. </p>
                </div>
            </div>
        </section><!-- #about close -->
        <!-- 
        About start
        ==================== -->

        <!-- 
        Service start
        ==================== -->
        <section id="service" class="section">
            <div class="container">
                <div class="row">
                    <div class="heading wow fadeInUp">
                        <h2>How to use Seembu?</h2>
                    </div>
                    <div class="col-sm-12 col-md-4 wow fadeInLeft" data-wow-delay="0.3s">
                        <div class="service">
                            <div class="icon-box">
                                <span class="icon">
                                    <i class="fa fa-lightbulb-o fa-4x"></i>   
                                </span>
                            </div>
                            <div class="caption">
                                <h3>Find Your Design Preference</h3>
                                <p>Browse finished projects of building professional.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-4 wow fadeInLeft" data-wow-delay="0.6s">
                        <div class="service">
                            <div class="icon-box">
                                <span class="icon">
                                    <i class="fa fa-users fa-4x"></i>   
                                </span>
                            </div>
                            <div class="caption">
                                <h3>Check Out Building Experts</h3>
                                <p>Check the expert's profile and examine the expert by reading their reviews.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-4 wow fadeInLeft" data-wow-delay="0.9s">
                        <div class="service">
                            <div class="icon-box">
                                <span class="icon">
                                    <i class="fa fa-phone-square fa-4x"></i>   
                                </span>
                            </div>
                            <div class="caption">
                                <h3>Get connected with professionals</h3>
                                <p>Get contract number of the expert then schedule for an appointment.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- .container close -->
        </section><!-- #service close -->

        <!-- 
        Projects start
        ==================== -->
        <section id="latest-projects" class="section">
            <div class="container">
                <h2 class="wow fadeInUp"> Latest Projects </h2>
                <main class="main-area">
                    <div class="centered">

                      <section class="cards">
                        <% @projects.each do |project| %>
                        <article class="card">
                          <span class="hover">
                            <figure class="thumbnail">
                            <% project.project_attachments.find(1) do |p| %>
                                <%= image_tag p.picture.url(:medium) %>
                            <% end %>

                                <!-- <div class="avatar-user-container">
                                  <%# image_tag project.user.profile.avatar.url(:thumb) %>
                                </div> -->
                                <div class="utilities-project">
                                  <% if user_signed_in? and current_user.id == project.user.id %>
                                    <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" do %>
                                      <i class="fa fa-trash" aria-hidden="true"></i>
                                    <% end %>
                                    <%= link_to edit_project_path(project), class: "btn btn-success pull-right " do %>
                                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                    <% end %>
                                  <% end %>
                                </div>
                            </figure>
                            <div class="card-content">
                              <div class="card-details">
                                <div class="project-title-index">
                                  <%= project.title %>  
                                </div>
                                <div class="user-fullname">
                                  by: <%= link_to profile_path(project.user.profile) do %>
                                    <span class="fullname"><%= project.user.profile.firmname %></span>
                                  <% end %>
                                </div> </br>
                                <div class="card-project-description">
                                  <strong>Description: </strong></br>
                                  <%= truncate( project.description , length: 35, omission: '...') %>
                                </div>
                                <div class="go-to-project">
                                  <%= link_to "Show Project" ,project, class: "btn btn-default btn-project-index-open" %> 
                                </div>
                              </div>
                            </div>
                            <!-- .card-content -->
                          </span>
                        </article>
                        <% end %>
                      <!-- .card -->
                      </section>
                      
                    <div class="button-for-see-more">
                        <%= link_to 'SEE MORE', projects_path, class: "btn btn-default btn-seemore pull-right" %>
                    </div>

                    </div>
                </main>
            </div>
        </section>
        <!-- 
        Call to action start
        ==================== -->        
        <section id="register" class="call-to-action-container">
        	<h2 class="text-center wow fadeInUp"> Register now! </h2>
        	<div class="container">
        		<div class="auth-container text-center">
        			<span class="btn-container-prehome"><%= link_to 'View More Projects', projects_path, class: "wow fadeInLeft btn btn-default btn-seemore" %></span>
        			<span class="btn-container-prehome"><%= link_to 'Register New Account', user_choose_path, class: "wow fadeInLeft btn btn-default btn-seemore" %></span>
        			<span class="btn-container-prehome"><%= link_to 'Login To Account', new_user_session_path, class: "wow fadeInLeft btn btn-default btn-seemore" %></span>
        		</div>
        	</div>
        </section>