config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:index, :edit, :show, :update] do
    resources :reviews
    resources :contacts, only: [:new, :create]
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get "professional/register" =>"registrations#professional_register"
    get "user/choose" => "registrations#choose"
  end

  resources :projects do
    # member do
    #   put "like" => "projects#upvote"
    # end
  end

  resources :project_attachments, only: [:edit, :update]

  #root 'projects#index'

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  root 'prehome#index'
  # get '*path' => redirect('/')

  #Additional Pages for sorting out projects and professional
    #Projects
    match 'commercials' => 'projects#commercials', :via => :get
    match 'residentials' => 'projects#residentials', :via => :get
    match 'offices' => 'projects#offices', :via => :get

    #Profile
    match 'professional/architects' => 'profiles#architects', :via => :get
    match 'professional/intdesigner' => 'profiles#interior_designers', :via => :get
    match 'professional/architect-firms' => 'profiles#architect_firms', :via => :get
    match 'professional/intdesigner-firms' => 'profiles#architect_firms', :via => :get
    match 'professional/design-firms' => 'profiles#design_firms', :via => :get
    match 'professional/land-architects' => 'profiles#land_architects', :via => :get
    match 'professional/gen-contractors' => 'profiles#gen_contractors', :via => :get
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base

	mount_uploader :avatar, AvatarUploader

	extend FriendlyId
	  friendly_id :firmname, use: :slugged

	 # User Avatar Validation
    validates_integrity_of  :avatar
    validates_processing_of :avatar

	belongs_to :user
    validates :avatar, file_size: { less_than_or_equal_to: 2.megabytes } 

    has_many :reviews, dependent: :destroy
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_action :edit_profile, only: [:edit]
  before_action :set_profile, only: [:update, :show]
  before_action :authenticate_user!, except: [:index, :show, :architects, :interior_designers, :design_firms, :architect_firms, :land_architects, :gen_contractors]

  # GET /profiles
  # GET /profiles.json
  def index

    # Conditional for current users
    if user_signed_in? and current_user.has_role?(:Professional)
      if current_user.profile.lname.blank? and current_user.profile.fname.blank?
        redirect_to edit_profile_path(current_user)
      end
    end

    @users = Profile.all

    @q = Profile.ransack(params[:q])
    @people = @q.result(distinct: true).order("created_at DESC")

  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show


    # Conditional for current users
    if user_signed_in? and current_user.has_role?(:Professional)
      if current_user.profile.lname.blank? and current_user.profile.fname.blank?
        redirect_to edit_profile_path(current_user)
      end
    end


    @projects = @profile.user.projects.order("created_at DESC").paginate(:page => params[:page], :per_page => 8)

    @gallery = @profile.user.projects

    if @profile.reviews.blank?
      @average_reviews = 0
    else
      @average_reviews = @profile.reviews.average(:rating).round(2)
    end

  end


  # GET /profiles/1/edit
  def edit
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  #Additional pages
  def architects
    @architects = Profile.where(service: "Architect")
  end

  def interior_designers
    @intdesigners = Profile.where(service: "Interior Designer")
  end

  def architect_firms
    @archfirms = Profile.where(service: "Architectural Firm")
  end

  def intdesign_firms
    @intdesfirms = Profile.where(service: "Interior Designing Firm")
  end

  def design_firms
    @desfirms = Profile.where(service: "Design & Build Firm")
  end

  def land_architects
    @landarchs = Profile.where(service: "Landscape Architect")
  end

  def gen_contractors
    @genconts = Profile.where(service: "General Contractor")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def edit_profile
      @profile = Profile.friendly.find_by(user_id: params[:id])
    end

    def set_profile
      @profile = Profile.friendly.find params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:fname, :lname, :address, :contactno, :service, :description, :avatar,
                                       :avatar_cache, :remove_avatar, :service_provided, :areas_served, :license_no, :awards,
                                       :sex, :occupation, :birthdate, :fbacc, :twacc, :website)
    end
end

app/helpers/profile_helper.rb
module ProfileHelper
	def full_name_portfolio
		@profile.fname + " " + @profile.lname
	end

end

app/views/profiles/_header.html.erb
<section id="hero-area">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <div class="content-block">
            <h1 class="wow fadeInDown">Seembu</h1>
            <p class="wow fadeInDown hero-area-subtitle" data-wow-delay="0.3s"> Seek Inspiration | Meet Professionals | Build Dreams</p>
          </div>
        </div>
      </div><!-- .row close -->
    </div><!-- .container close -->
  </section><!-- header close -->
<%= render 'layouts/navbar_header' %>

app/views/profiles/architect_firms.html.erb
<%= render 'header' %>

<section class="pro-section">
  <% @archfirms.each do |arc| %>
  <div class="container">
    <div class="row pro-cards wow fadeInUp" data-wow-delay="0.8s">
        <div class="col-xs-6 col-md-2 thumbnail-row">
          <div class="pro-thumbnail">
            <% if arc.avatar.blank? %>
              <img src="https://s25.postimg.org/d8ua0awj3/13672276_10202065347873149_1662064195_n.jpg" class="img-default-pro"></img>
            <% else %>
              <%= image_tag arc.avatar.url(:small) %>
            <% end %>
          </div>
          </div>
          <div class="col-xs-6 col-md-10">
            <div class="pro-content">
              <div class="pro-name-index">
                <%= link_to profile_path( arc ) do %>
                  <h3><%= arc.firmname %></h3>
                <% end %>
                <span class="user-service"><%= arc.service %> </span>

                  <div class="profile-index-ss-container">

                    <% if arc.fbacc.blank? %>
                      <div class="fb-position-index" hidden>
                        <a href="<%= arc.fbacc %>" hidden>
                          <i class="fa fa-2x fa-facebook-official" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% else %>
                      <div class="fb-position-index">
                      <a href="<%= arc.fbacc %>">
                        <i class="fa fa-2x fa-facebook-official" aria-hidden="true"></i>
                      </a>
                    </div>
                    <% end %>

                    <% if arc.twacc.blank? %>
                      <div class="tw-position-index" hidden>
                        <a href="<%= arc.twacc %>" hidden>
                          <i class="fa fa-2x fa-twitter" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% else %>
                      <div class="tw-position-index">
                        <a href="<%= arc.twacc %>">
                          <i class="fa fa-2x fa-twitter" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% end %>

                    <% if arc.website.blank? %>
                      <div class="web-position-index" hidden>
                        <a href="<%= arc.website %>" hidden>
                          <i class="fa fa-2x fa-desktop" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% else %>
                      <div class="web-position-index">
                        <a href="<%= arc.website %>">
                          <i class="fa fa-2x fa-desktop" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% end %>

                    </div>
                </div>

              </div></br>
              <div class="card-project-areas">
                <div class="row">
                  <div class="col-md-3">
                    <strong>Services: </strong></br>
                    <span class="portfolio-field" ><%= arc.service_provided %></span>
                  </div>
                  <div class="col-md-3">
                    <strong>Email Address: </strong></br>
                    <span class="portfolio-field" ><%= arc.user.email %></span>
                  </div>
                  <div class="col-md-3">
                    <strong>Areas Serviced: </strong></br>
                    <span class="portfolio-field" ><%= arc.areas_served %></span>
                  </div>
                  <div class="col-md-3">
                    <strong>Business Address: </strong></br>
                    <span class="portfolio-field" ><%= arc.address %></span>
                  </div>
                </div>
              </div>
            </div>
          </div></br>
        </div>
  <% end %>
</section>

app/views/profiles/architects.html.erb
<%= render 'header' %>

<section class="pro-section">
  <% @architects.each do |arc| %>
  <div class="container">
    <div class="row pro-cards wow fadeInUp" data-wow-delay="0.8s">
        <div class="col-xs-6 col-md-2 thumbnail-row">
          <div class="pro-thumbnail">
            <% if arc.avatar.blank? %>
              <img src="https://s25.postimg.org/d8ua0awj3/13672276_10202065347873149_1662064195_n.jpg" class="img-default-pro"></img>
            <% else %>
              <%= image_tag arc.avatar.url(:small) %>
            <% end %>
          </div>
          </div>
          <div class="col-xs-6 col-md-10">
            <div class="pro-content">
              <div class="pro-name-index">
                <%= link_to profile_path( arc ) do %>
                  <h3><%= arc.fname %> <%= arc.lname %></h3>
                <% end %>
                <span class="user-service"><%= arc.service %> </span>

                  <div class="profile-index-ss-container">

                    <% if arc.fbacc.blank? %>
                      <div class="fb-position-index" hidden>
                        <a href="<%= arc.fbacc %>" hidden>
                          <i class="fa fa-2x fa-facebook-official" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% else %>
                      <div class="fb-position-index">
                      <a href="<%= arc.fbacc %>">
                        <i class="fa fa-2x fa-facebook-official" aria-hidden="true"></i>
                      </a>
                    </div>
                    <% end %>

                    <% if arc.twacc.blank? %>
                      <div class="tw-position-index" hidden>
                        <a href="<%= arc.twacc %>" hidden>
                          <i class="fa fa-2x fa-twitter" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% else %>
                      <div class="tw-position-index">
                        <a href="<%= arc.twacc %>">
                          <i class="fa fa-2x fa-twitter" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% end %>

                    <% if arc.website.blank? %>
                      <div class="web-position-index" hidden>
                        <a href="<%= arc.website %>" hidden>
                          <i class="fa fa-2x fa-desktop" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% else %>
                      <div class="web-position-index">
                        <a href="<%= arc.website %>">
                          <i class="fa fa-2x fa-desktop" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% end %>

                    </div>
                </div>

              </div></br>
              <div class="card-project-areas">
                <div class="row">
                  <div class="col-md-3">
                    <strong>Services: </strong></br>
                    <span class="portfolio-field" ><%= arc.service_provided %></span>
                  </div>
                  <div class="col-md-3">
                    <strong>Email Address: </strong></br>
                    <span class="portfolio-field" ><%= arc.user.email %></span>
                  </div>
                  <div class="col-md-3">
                    <strong>Areas Serviced: </strong></br>
                    <span class="portfolio-field" ><%= arc.areas_served %></span>
                  </div>
                  <div class="col-md-3">
                    <strong>Business Address: </strong></br>
                    <span class="portfolio-field" ><%= arc.address %></span>
                  </div>
                </div>
              </div>
            </div>
          </div></br>
        </div>
  <% end %>
</section>

app/views/profiles/design_firms.html.erb
<%= render 'header' %>

<section class="pro-section">
  <% @desfirms.each do |arc| %>
  <div class="container">
    <div class="row pro-cards wow fadeInUp" data-wow-delay="0.8s">
        <div class="col-xs-6 col-md-2 thumbnail-row">
          <div class="pro-thumbnail">
            <% if arc.avatar.blank? %>
              <img src="https://s25.postimg.org/d8ua0awj3/13672276_10202065347873149_1662064195_n.jpg" class="img-default-pro"></img>
            <% else %>
              <%= image_tag arc.avatar.url(:small) %>
            <% end %>
          </div>
          </div>
          <div class="col-xs-6 col-md-10">
            <div class="pro-content">
              <div class="pro-name-index">
                <%= link_to profile_path( arc ) do %>
                  <h3><%= arc.firmname %></h3>
                <% end %>
                <span class="user-service"><%= arc.service %> </span>

                  <div class="profile-index-ss-container">

                    <% if arc.fbacc.blank? %>
                      <div class="fb-position-index" hidden>
                        <a href="<%= arc.fbacc %>" hidden>
                          <i class="fa fa-2x fa-facebook-official" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% else %>
                      <div class="fb-position-index">
                      <a href="<%= arc.fbacc %>">
                        <i class="fa fa-2x fa-facebook-official" aria-hidden="true"></i>
                      </a>
                    </div>
                    <% end %>

                    <% if arc.twacc.blank? %>
                      <div class="tw-position-index" hidden>
                        <a href="<%= arc.twacc %>" hidden>
                          <i class="fa fa-2x fa-twitter" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% else %>
                      <div class="tw-position-index">
                        <a href="<%= arc.twacc %>">
                          <i class="fa fa-2x fa-twitter" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% end %>

                    <% if arc.website.blank? %>
                      <div class="web-position-index" hidden>
                        <a href="<%= arc.website %>" hidden>
                          <i class="fa fa-2x fa-desktop" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% else %>
                      <div class="web-position-index">
                        <a href="<%= arc.website %>">
                          <i class="fa fa-2x fa-desktop" aria-hidden="true"></i>
                        </a>
                      </div>
                    <% end %>

                    </div>
                </div>

              </div></br>
              <div class="card-project-areas">
                <div class="row">
                  <div class="col-md-3">
                    <strong>Services: </strong></br>
                    <span class="portfolio-field" ><%= arc.service_provided %></span>
                  </div>
                  <div class="col-md-3">
                    <strong>Email Address: </strong></br>
                    <span class="portfolio-field" ><%= arc.user.email %></span>
                  </div>
                  <div class="col-md-3">
                    <strong>Areas Serviced: </strong></br>
                    <span class="portfolio-field" ><%= arc.areas_served %></span>
                  </div>
                  <div class="col-md-3">
                    <strong>Business Address: </strong></br>
                    <span class="portfolio-field" ><%= arc.address %></span>
                  </div>
                </div>
              </div>
            </div>
          </div></br>
        </div>
  <% end %>
</section>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

app/views/profiles/show.html.erb
<section class="profile-section">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-sm-12 sidebar ">
        <div class="portfolio-section wow fadeInDown" data-wow-delay="0.3s">
          <div class="portfolio-container">  
            <div class="portfolio-avatar">
              <% if @profile.avatar.blank? %>
                <img src="https://s25.postimg.org/d8ua0awj3/13672276_10202065347873149_1662064195_n.jpg" class="img-default"></img>
              <% else %>
                 <%= image_tag @profile.avatar.url(:small)%>
              <% end %>
            </div>
            <div class="portfolio-name">
              <!-- <%# if @profile.fname.blank? or @profile.lname.blank? %>
                <h4> <%# @profile.user.email %> </h4>
              <%# else %>
              <h2><%# full_name_portfolio %></h2>
              <%# end %> -->
              <h2><%= @profile.firmname %></h2>
              <% if @profile.user.has_role? :Professional %>
                <span class="portfolio-service"><%= @profile.service %></span>
                <%if @profile.reviews.blank? %>
                  <div hidden></div>
                <% else %>
                  <div class="average-review-rating" data-score="<%= @average_reviews %>" ></div>
                <% end %>

              <% end %>
            </div></br>
            <div class="portfolio-description">
              <p class="minimize text-center">
                <%= @profile.description %>
              </p> </br>
            </div>
            <div class="portfolio-divider"></div>
            <div class="portfolio-details-container">

              <div class="portfolio-details-section">
                <span class="label"> Email: </span></br>
                <span class="portfolio-field"><%= @profile.user.email %></span>
              </div>

              <div class="portfolio-details-section">
                <span class="label"> Address: </span> </br>
                <span class="portfolio-field"><%= @profile.address %></span>
              </div>
              <% if @profile.user.has_role? :Professional %>
                <% if @profile.service_provided.blank? %>
                  <div class="portfolio-details-section" hidden >
                    <span class="label" hidden > Service Provided: </span> </br>
                    <span class="portfolio-field" hidden ><%= @profile.service_provided %></span>
                  </div>
                <% else %>
                  <div class="portfolio-details-section">
                    <span class="label"> Service Provided: </span> </br>
                    <span class="portfolio-field"><%= @profile.service_provided %></span>
                  </div>
                <% end %>

                <% if @profile.areas_served.blank? %>
                  <div class="portfolio-details-section" hidden >
                    <span class="label" hidden > Areas Served: </span> </br>
                    <span class="portfolio-field" hidden ><%= @profile.areas_served %></span>
                  </div>
                <% else %>
                  <div class="portfolio-details-section">
                    <span class="label"> Areas Served: </span> </br>
                    <span class="portfolio-field"><%= @profile.areas_served %></span>
                  </div>
                <% end %>

                <% if @profile.license_no.blank? %>
                  <div class="portfolio-details-section" hidden>
                    <span class="label" hidden> License Number: </span></br>
                    <span class="portfolio-field" hidden ><%= @profile.license_no %></span>
                  </div>
                <% else %>
                  <div class="portfolio-details-section">
                    <span class="label"> License Number: </span></br>
                    <span class="portfolio-field"><%= @profile.license_no %></span>
                  </div>
                <% end %>

                <%if @profile.awards.blank? %>
                  <div class="portfolio-details-section" hidden>
                    <span class="label" hidden> Awards: </span></br>
                    <span class="portfolio-field" hidden><%= @profile.awards %></span>
                  </div>
                <% else %>
                  <div class="portfolio-details-section">
                    <span class="label"> Awards: </span></br>
                    <span class="portfolio-field"><%= @profile.awards %></span>
                  </div>
                <% end %>

                <div class="link-to-contacts">
                  <%= link_to "Contact Me", new_profile_contact_path(@profile), class: "btn btn-default btn-project-open btn-block" %>
                </div>

                
              <% elsif @profile.user.has_role? :Client %>

                <% if @profile.sex.blank? %>
                  <div class="portfolio-details-section" hidden >
                    <span class="label" hidden > Gender: </span> </br>
                    <span class="portfolio-field" hidden ><%= @profile.sex %></span>
                  </div>
                <% else %>
                  <div class="portfolio-details-section">
                    <span class="label"> Gender: </span> </br>
                    <span class="portfolio-field"><%= @profile.sex %></span>
                  </div>
                <% end %>

                <% if @profile.birthdate.blank? %>
                  <div class="portfolio-details-section" hidden>
                    <span class="label" hidden> Birthday: </span></br>
                    <span class="portfolio-field" hidden ><%= @profile.birthdate %></span>
                  </div>
                <% else %>
                  <div class="portfolio-details-section">
                    <span class="label">  Birthday: </span></br>
                    <span class="portfolio-field"><%= @profile.birthdate %></span>
                  </div>
                <% end %>

                <%if @profile.occupation.blank? %>
                  <div class="portfolio-details-section" hidden>
                    <span class="label" hidden> Occupation: </span></br>
                    <span class="portfolio-field" hidden><%= @profile.occupation %></span>
                  </div>
                <% else %>
                  <div class="portfolio-details-section">
                    <span class="label"> Occupation: </span></br>
                    <span class="portfolio-field"><%= @profile.occupation %></span>
                  </div>
                <% end %>
              <% end %>

            </div>
          </div>
        </div> </br>

        <% if @profile.user.has_role? :Professional %>
          <div class="gallery-container wow fadeInUp" data-wow-delay="0.5s">
            <div class="gallery-section">
              <h2 class="gallery-sign">Project Gallery</h2></br>
              <ul id="lightGallery" class="flex-gallery">
              <% @gallery.each do |gallery| %>
                <% gallery.project_attachments.each do |img| %>
                  <li class="gallery-flex" data-src="<%= img.picture.url %>">
                      <%= image_tag img.picture.url(:small), class: "img-responsive" %>
                  </li>
                <% end %>
              <% end %>
            </ul>
            </div>
          </div>

          <div class="gallery-container wow fadeInUp" data-wow-delay="0.9s">
            <div class="gallery-section">
              <h2 class="gallery-sign"> <%= @profile.reviews.count %> Reviews </h2></br>
                <%= render @reviews = @profile.reviews.order("created_at DESC").paginate(:page => params[:page], :per_page => 3) %>

                <%= will_paginate @reviews %>

                <div>
                  <%= link_to "Add Reviews", new_profile_review_path(@profile), class: "btn btn-default btn-project-open" %> 
                </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="col-md-8 col-sm-12 main-bg">
        <% @projects.each do |project| %>
          <div class="project-container-profile">
            <div class="project-card-profile wow fadeIn" data-wow-delay="0.8s">
              <div class="img-container-projects">
              <% project.project_attachments.find(1) do |p| %>
                  <%= image_tag p.picture.url(:medium), class: "img-responsive" %>
                <% end %>
                  <% if user_signed_in? and current_user.id == project.user.id %>
                    <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-embed-trash btn btn-danger" do %>
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    <% end %>
                    <%= link_to edit_project_path( project ), class: "btn-embed-edit btn btn-success" do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    <% end %>
                  <% end %>

                <!-- <div class="like-section">
                  <%# link_to like_project_path(project),  class: "like-show-profile btn pull-right", method: :put do %>
                    <button type="button" class="btn btn-like" aria-label="Left Align">
                      <span class="fa fa-heart glyphicon-align-center" aria-hidden="true"></span>
                      <span class="badge"><%# project.get_upvotes.size %></span>
                    </button>
                  <%# end %>
                </div> -->

              </div>
              <div class="details-container-projects">
                  <h2 class="project-title-details"><%= project.title %></h2>
                  <div class="details-section-projects">
                    <div class="minimize">
                      <h5><%= project.description %></h5>
                  </div>
                  <%= link_to 'OPEN PROJECT', project_path( project ), class: "btn btn-default btn-project-open" %>
              </div>
            </div>
          </div>
        <% end %>
        <%= will_paginate @projects, previous_label: "New", next_label: "Older" %>
      </div>
    </div>
  </div>
</section>

<script type="text/javascript">
  $(document).ready(function() {
    $("#lightGallery").lightGallery();

    $('.minimize').readmore({
      speed: 400,
      lessLink: '<a href="#" class="text-center">Close</a>',
      moreLink: '<a href="#" class="text-center">Read more</a>'
    });

    $('.review-rating').raty({
      readOnly: true,
      score: function(){
        return $(this).attr('data-score');
      },
      starHalf: 'fa fa-fw fa-star-half-o',
      starOff: 'fa fa-fw fa-star-o',
      starOn: 'fa fa-fw fa-star'
    });

    $('.average-review-rating').raty({
    readOnly: true,
    score: function(){
      return $(this).attr('data-score')
    },
      starHalf: 'fa fa-fw fa-star-half-o fa-2x star-color',
      starOff: 'fa fa-fw fa-star-o fa-2x star-color',
      starOn: 'fa fa-fw fa-star fa-2x star-color'
    }); 

  });

</script>