config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:index, :edit, :show, :update] do
    resources :reviews
    resources :contacts, only: [:new, :create]
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get "professional/register" =>"registrations#professional_register"
    get "user/choose" => "registrations#choose"
  end

  resources :projects do
    # member do
    #   put "like" => "projects#upvote"
    # end
  end

  resources :project_attachments, only: [:edit, :update]

  #root 'projects#index'

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  root 'prehome#index'
  # get '*path' => redirect('/')

  #Additional Pages for sorting out projects and professional
    #Projects
    match 'commercials' => 'projects#commercials', :via => :get
    match 'residentials' => 'projects#residentials', :via => :get
    match 'offices' => 'projects#offices', :via => :get

    #Profile
    match 'professional/architects' => 'profiles#architects', :via => :get
    match 'professional/intdesigner' => 'profiles#interior_designers', :via => :get
    match 'professional/architect-firms' => 'profiles#architect_firms', :via => :get
    match 'professional/intdesigner-firms' => 'profiles#architect_firms', :via => :get
    match 'professional/design-firms' => 'profiles#design_firms', :via => :get
    match 'professional/land-architects' => 'profiles#land_architects', :via => :get
    match 'professional/gen-contractors' => 'profiles#gen_contractors', :via => :get
  
end

app/models/project.rb
class Project < ActiveRecord::Base

	#acts_as_votable

	has_many :project_attachments, dependent: :destroy
    accepts_nested_attributes_for :project_attachments

	extend FriendlyId
  		friendly_id :title, use: :slugged

	belongs_to :user

	def picture_file_type
		Project_Attachments.picture
	end

	#Validations
	validates :title, presence: true
	validates :size, presence: true
	validates :project_type, presence: true
	validates :year_finished, presence: true,
		  inclusion: { in: 1900..Date.today.year },
		  format: { 
		    with: /(19|20)\d{2}/i, 
		    message: "should be a four-digit year"
		  }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show, :commercials, :residentials, :offices]

  # GET /projects
  # GET /projects.json
  def index

    # Conditional for current users
    if user_signed_in? and current_user.has_role?(:Professional)
      if current_user.profile.lname.blank? and current_user.profile.fname.blank?
        redirect_to edit_profile_path(current_user)
      end
    end

    @project_attachments = ProjectAttachment.all

    @search = Project.search(params[:q])
    @projects = @search.result.order("created_at DESC").paginate(:page => params[:page], :per_page => 6)
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project_attachments = @project.project_attachments.all

    if @project.user.profile.reviews.blank?
      @average_reviews = 0
    else
      @average_reviews = @project.user.profile.reviews.average(:rating).round(2)
    end
  end

  # GET /projects/new
  def new

    # Conditional for current users
    if user_signed_in? and current_user.has_role?(:Professional)
      if current_user.profile.lname.blank? and current_user.profile.fname.blank?
        redirect_to edit_profile_path(current_user), notice: "Please fill the required input."
      end
    end

    @project = current_user.projects.build
    @project_attachment = @project.project_attachments.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        params[:project_attachments]['picture'].each do |a|
          @project_attachment = @project.project_attachments.create!(:picture => a)
        end
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #Acts as votable 
  # def upvote
  #   @project.upvote_from current_user
  #   redirect_to :back
  # end

  #Additional Pages
  def commercials
    @commercials = Project.where(project_type: "Commercial").order("created_at DESC")
  end

  def residentials
    @residentials = Project.where(project_type: "Residential").order("created_at DESC")
  end

  def offices
    @offices = Project.where(project_type: "Office").order("created_at DESC")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :room, :location, :style, :size, :description, :project_type, :year_finished, :slug, project_attachments_attributes: [:id, :project_id, :picture])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def full_name
		@project.user.profile.fname + " " + @project.user.profile.lname
	end

end

app/views/projects/_form.html.erb
<section class="form-section">
  <div class="form-container">
    <div class="form-page">
      <div class="auth-form">
          <%= form_for(@project, :html => { :multipart => true }) do |f| %>
          <% if @project.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

              <ul>
              <% @project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <h2>Post Your Project</h2></br>

          <%= f.fields_for :project_attachments do |p| %>
           <div class="field">
             <label class="form-label">Upload Picture/s Of Your Projects: </label>
             <%= p.file_field :picture, :multiple => true, name: "project_attachments[picture][]", accept: "image/png, image/jpg, image/jpeg", required: true %>
           </div>
         <% end %>
         
          <%= f.text_field :title, placeholder: "Title Of This Project", required: true %>

          <label class="form-label">Room Size: </label>
          <%= f.select(:size, options_for_select([['Compact'], ['Medium'], ['Large'], ['Expansive']]), class: "full-width-select")%>
          <label class="form-label">Type of Project: </label>
          <%= f.select(:project_type, options_for_select([['Residential'], ['Commercial'], ['Office']]), class: "full-width-select", required: true )%>
          
          <%= f.text_field :location, placeholder: "City", required: true %>
          <%= f.text_field :year_finished, placeholder: "Year Finished", required: true %>
          <%= f.text_field :style, placeholder: "Style / Theme" %>

          <%= f.text_area :description, placeholder: "Short Description", class: "form-description" %>

          <div class="actions">
            <%= f.submit "POST", class: "submit-action" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/projects/_form_edit.html.erb
<section class="form-section">
  <div class="form-container">
    <div class="form-page">
      <div class="auth-form">
          <%= form_for(@project) do |f| %>
          <% if @project.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

              <ul>
              <% @project.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <h2>Post Your Project</h2></br>
          <label class="form-label">Title: </label>
          <%= f.text_field :title, placeholder: "Title Of This Project", required: true %>
          <label class="form-label">Year Finished: </label>
          <%= f.text_field :year_finished, placeholder: "Year Finished", required: true %>
          <label class="form-label">Location Of Project: </label>
          <%= f.text_field :location, placeholder: "City", required: true %>
          <label class="form-label">Theme/Style Of Project: </label>
          <%= f.text_field :style, placeholder: "Style / Theme" %>

          <label class="form-label">Room Size: </label>
          <%= f.select(:size, options_for_select([['Compact'], ['Medium'], ['Large'], ['Expansive']]), required: true )%>
          <label class="form-label">Type of Project: </label>
          <%= f.select(:project_type, options_for_select([['Residential'], ['Commercial'], ['Office']]), required: true )%>

          <label class="form-label">Description Of Project: </label>
          <%= f.text_area :description, placeholder: "Short Description", class: "form-description" %>

          <div class="actions">
            <%= f.submit "UPDATE", class: "submit-action" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/projects/_header_add_pages.html.erb
<section id="hero-area">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <div class="content-block">
            <h1 class="wow fadeInDown">Seembu</h1>
            <p class="wow fadeInDown hero-area-subtitle" data-wow-delay="0.3s"> Seek Inspiration | Meet Professionals | Build Dreams</p>
          </div>
        </div>
      </div><!-- .row close -->
    </div><!-- .container close -->
  </section><!-- header close -->
<%= render 'layouts/navbar_header' %>

app/views/projects/_headerone.html.erb
<section id="hero-area">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <div class="content-block">
            <h1 class="wow fadeInDown">Seembu</h1>
            <p class="wow fadeInDown hero-area-subtitle" data-wow-delay="0.3s"> Seek Inspiration | Meet Professionals | Build Dreams</p>
          </div>
        </div>
        <div class="col-md-6 col-sm-12">
          <div class="block">
            <h2 class="text-center"> Searching for something? </h2> </br>
              <%= search_form_for(@search, class: "text-center")  do |f| %>
                <fieldset class="search-form">
                  <%= f.text_field :title_or_location_or_style_or_size_or_project_type_cont, placeholder: "Modern, Manila, Living room?", type: "search", class: "search-input" %>
                  <%= button_tag(type: 'submit', class: "btn-search") do %>
                   <i class="fa fa-search"></i>
                  <% end %>
                </fieldset>
              <% end %>
        </div>
        </div>
      </div><!-- .row close -->
    </div><!-- .container close -->
  </section><!-- header close -->
<%= render 'layouts/navbar_header' %>

app/views/projects/_headertres.html.erb
<section id="hero-area">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <div class="content-block">
            <h1 class="wow fadeInDown">Seembu</h1>
            <p class="wow fadeInDown hero-area-subtitle" data-wow-delay="0.3s"> Seek Inspiration | Meet Professionals | Build Dreams</p>
          </div>
        </div>
          <div class="col-md-6 col-sm-12">
                <div class="block">
                  <h2 class="text-center"> Searching for something? </h2> </br>
                    <%= search_form_for(@search, class: "text-center")  do |f| %>
                      <fieldset class="search-form">
                        <%= f.text_field :title_or_location_or_style_or_size_or_project_type_cont, placeholder: "Modern, Manila, Living room?", type: "search", class: "search-input" %>
                        <%= button_tag(type: 'submit', class: "btn-search") do %>
                         <i class="fa fa-search"></i>
                        <% end %>
                      </fieldset>
                    <% end %>
                  </div>
        </div>
      </div><!-- .row close -->
    </div><!-- .container close -->
  </section><!-- header close -->
  <%= render 'layouts/navbar_header' %>

app/views/projects/_headertwo.html.erb
<section id="hero-area">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-12">
          <div class="content-block">
            <h1 class="wow fadeInDown">Seembu</h1>
            <p class="wow fadeInDown hero-area-subtitle" data-wow-delay="0.3s"> Seek Inspiration | Meet Professionals | Build Dreams</p>
          </div>
        </div>
          <div class="col-md-6 col-sm-12">
            <% if current_user.profile.service.blank? %>
                <div class="block">
                  <h4 class="text-center"> Welcome Building Professionals! </h4></br>
                  <p class="text-center"> I am your helper and I will help you setup your Seembu account. </p>
                  <p> Currently, we are still in our <em>beta phase</em> at this time and we are thankful that you are part of our early stage platform. We will continue to <strong>improve in serving you</strong> so please don't hesitate to leave us your feedback. </p> </br>
                  <h3> Right now, you'll need fill up your <strong>personal details. </strong></h3>
                    <li> Press <strong><em>"My Accounts"</em></strong> which can be located on the top navbar.</li>
                    <li> Locate <strong><em>"Edit My Profile", and click.</em></strong> </li>
                    <li> Or, click the <strong><em>BUTTON BELLOW</em></strong> </li>
                  <%= link_to('EDIT MY PROFILE', edit_profile_path( current_user.profile ) , class: "btn btn-default btn-home" )%>
                </div>
            <% else %>
                <div class="block">
                  <h2 class="text-center"> Searching for something? </h2> </br>
                    <%= search_form_for(@search, class: "text-center")  do |f| %>
                      <fieldset class="search-form">
                        <%= f.text_field :title_or_location_or_style_or_size_or_project_type_cont, placeholder: "Modern, Manila, Living room?", type: "search", class: "search-input" %>
                        <%= button_tag(type: 'submit', class: "btn-search") do %>
                         <i class="fa fa-search"></i>
                        <% end %>
                      </fieldset>
                    <% end %>
                  </div>
            <% end %>
        </div>
      </div><!-- .row close -->
    </div><!-- .container close -->
  </section><!-- header close -->
  <%= render 'layouts/navbar_header' %>

app/views/projects/commercials.html.erb
<%= render 'header_add_pages' %>

<div class="container">
  <main class="main-area">
    <div class="centered">
      <section class="cards">
        <% @commercials.each do |project| %>
        <article class="card wow fadeInUp" data-wow-delay="0.8s">
          <span class="hover">
            <figure class="thumbnail">
              <% project.project_attachments.find(1) do |p| %>
                  <%= image_tag p.picture.url(:medium) %>
                <% end %>
                <!-- <div class="avatar-user-container">
                  <%# image_tag project.user.profile.avatar.url(:thumb) %>
                </div> -->
                <div class="utilities-project">
                  <% if user_signed_in? and current_user.id == project.user.id %>
                    <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" do %>
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    <% end %>
                    <%= link_to edit_project_path(project), class: "btn btn-success pull-right " do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    <% end %>
                  <% end %>
                </div>
            </figure>
            <div class="card-content">
              <div class="card-details">
                <div class="project-title-index">
                  <%= project.title %>  
                </div>
                <div class="user-fullname">
                  by: <%= link_to profile_path(project.user.profile) do %>
                    <span class="fullname"><%= project.user.firmname %></span>
                  <% end %>
                </div> </br>
                <div class="card-project-description">
                  <strong>Description: </strong></br>
                  <%= truncate( project.description , length: 35, omission: '...') %>
                </div>
                <div class="go-to-project">
                  <%= link_to "SHOW PROJECT" ,project, class: "btn btn-default btn-project-index-open" %> 
                </div>
              </div>
            </div>
            <!-- .card-content -->
          </span>
        </article>
        <% end %>
      <!-- .card -->
      </section>
    </div>
  </main>
</div>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<% if current_user.has_role? :Professional %>
	<%= render 'form_edit' %>
<% else %>
	<%= controller.redirect_to projects_path, alert: "We're sorry, we can't allow that." %>
<% end %>

app/views/projects/index.html.erb
<% if user_signed_in? and current_user.has_role? :Professional %>
  <%= render 'headertwo' %>
<% elsif user_signed_in? and current_user.has_role? :Client %>
  <%= render 'headertres' %>
<% else %>
  <%= render 'headerone' %>
<% end %>

<div class="container">
  <main class="main-area">
    <div class="centered">
      <section class="cards">
        <% @projects.each do |project| %>
        <article class="card wow fadeInUp" data-wow-delay="0.8s">
          <span class="hover">
            <figure class="thumbnail">

              <!-- <%# link_to like_project_path(project),  class: "like btn pull-right", method: :put do %>
                <button type="button" class="btn btn-like" aria-label="Left Align">
                  <span class="fa fa-heart glyphicon-align-center" aria-hidden="true"></span>
                  <span class="badge"><%# project.get_upvotes.size %></span>
                </button>
              <%# end %> -->

                <% project.project_attachments.find(1) do |p| %>
                  <%= image_tag p.picture.url(:medium) %>
                <% end %>

                <!-- <div class="avatar-user-container">
                  <%# image_tag project.user.profile.avatar.url(:thumb) %>
                </div> -->
                <div class="utilities-project">
                  <% if user_signed_in? and current_user.id == project.user.id %>
                    <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" do %>
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    <% end %>
                    <%= link_to edit_project_path(project), class: "btn btn-success pull-right " do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    <% end %>
                  <% end %>
                </div>
            </figure>
            <div class="card-content">
              <div class="card-details">
                <div class="project-title-index">
                  <%= project.title %>  
                </div>
                <div class="user-fullname">
                  by: <%= link_to profile_path(project.user.profile) do %>
                    <span class="fullname"><%= project.user.profile.firmname %></span>
                  <% end %>
                </div> </br>
                <div class="card-project-description">
                  <strong>Description: </strong></br>
                  <%= truncate( project.description , length: 35, omission: '...') %>
                </div>
                <div class="go-to-project">
                  <%= link_to "SHOW PROJECT" ,project, class: "btn btn-default btn-project-index-open"%> 
                </div>
              </div>
            </div>
            <!-- .card-content -->
          </span>
        </article>
        <% end %>
      <!-- .card -->
      </section>
      <div class="pagination-index-container">
        <%= will_paginate @posts %>
      </div>
    </div>
  </main>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<% if current_user.has_role? :Professional %>
	<%= render 'form' %>
<% else %>
	<%= controller.redirect_to projects_path, alert: "We're sorry, we can't allow that." %>
<% end %>

app/views/projects/offices.html.erb
<%= render 'header_add_pages' %>

<div class="container">
  <main class="main-area">
    <div class="centered">
      <section class="cards">
        <% @offices.each do |project| %>
        <article class="card wow fadeInUp" data-wow-delay="0.8s">
          <span class="hover">
            <figure class="thumbnail">
              <% project.project_attachments.find(1) do |p| %>
                  <%= image_tag p.picture.url(:medium) %>
                <% end %>
                <!-- <div class="avatar-user-container">
                  <%# image_tag project.user.profile.avatar.url(:thumb) %>
                </div> -->
                <div class="utilities-project">
                  <% if user_signed_in? and current_user.id == project.user.id %>
                    <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" do %>
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    <% end %>
                    <%= link_to edit_project_path(project), class: "btn btn-success pull-right " do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    <% end %>
                  <% end %>
                </div>
            </figure>
            <div class="card-content">
              <div class="card-details">
                <div class="project-title-index">
                  <%= project.title %>  
                </div>
                <div class="user-fullname">
                  by: <%= link_to profile_path(project.user.profile) do %>
                    <span class="fullname"><%= project.user.firmname %></span>
                  <% end %>
                </div> </br>
                <div class="card-project-description">
                  <strong>Description: </strong></br>
                  <%= truncate( project.description , length: 35, omission: '...') %>
                </div>
                <div class="go-to-project">
                  <%= link_to "SHOW PROJECT" ,project, class: "btn btn-default btn-project-index-open" %> 
                </div>
              </div>
            </div>
            <!-- .card-content -->
          </span>
        </article>
        <% end %>
      <!-- .card -->
      </section>
    </div>
  </main>
</div>

app/views/projects/residentials.html.erb
<%= render 'header_add_pages' %>

<div class="container">
  <main class="main-area">
    <div class="centered">
      <section class="cards">
        <% @residentials.each do |project| %>
        <article class="card wow fadeInUp" data-wow-delay="0.8s">
          <span class="hover">
            <figure class="thumbnail">
              <% project.project_attachments.find(1) do |p| %>
                  <%= image_tag p.picture.url(:medium) %>
                <% end %>
                <!-- <div class="avatar-user-container">
                  <%# image_tag project.user.profile.avatar.url(:thumb) %>
                </div> -->
                <div class="utilities-project">
                  <% if user_signed_in? and current_user.id == project.user.id %>
                    <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger pull-right" do %>
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    <% end %>
                    <%= link_to edit_project_path(project), class: "btn btn-success pull-right " do %>
                      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                    <% end %>
                  <% end %>
                </div>
            </figure>
            <div class="card-content">
              <div class="card-details">
                <div class="project-title-index">
                  <%= project.title %>  
                </div>
                <div class="user-fullname">
                  by: <%= link_to profile_path(project.user.profile) do %>
                    <span class="fullname"><%= project.user.firmname %></span>
                  <% end %>
                </div> </br>
                <div class="card-project-description">
                  <strong>Description: </strong></br>
                  <%= truncate( project.description , length: 35, omission: '...') %>
                </div>
                <div class="go-to-project">
                  <%= link_to "SHOW PROJECT" ,project, class: "btn btn-default btn-project-index-open" %> 
                </div>
              </div>
            </div>
            <!-- .card-content -->
          </span>
        </article>
        <% end %>
      <!-- .card -->
      </section>
    </div>
  </main>
</div>

app/views/projects/show.html.erb
<section class="show-project-section">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-12">
        <div class="gallery single-item" oncontextmenu="return true;">

          <% @project_attachments.each do |p| %>
              <%= image_tag p.picture.url, :class => "img-responsive" %>
              <%# if user_signed_in? and current_user.id == @project.user.id %>
                <%# link_to "Edit Attachment", edit_project_attachment_path(p), class: "absolute-position"%>
              <%# end %>
          <% end %>

        </div>
        <!-- <div class="like-section">
            <%# link_to like_project_path(@project),  class: "like-show btn pull-right", method: :put do %>
              <button type="button" class="btn btn-like" aria-label="Left Align">
                <span class="fa fa-heart glyphicon-align-center" aria-hidden="true"></span>
                <span class="badge"><%# @project.get_upvotes.size %></span>
              </button>
            <%# end %>
        </div> -->
      </div>
      <div class="col-md-4 col-sm-12">
        <div class="project-details-container">
          <div class="project-details-section">
            <h2 class="title-project text-center"> <%= @project.title %> </h2></br>
            <div class="user-case-container">
              <div class="image-avatar-user">
              <% if @project.user.profile.avatar.blank? %>
                <img src="https://s25.postimg.org/d8ua0awj3/13672276_10202065347873149_1662064195_n.jpg" class="img-default-project-show"></img>
              <% else %>
                 <%= image_tag @project.user.profile.avatar.url(:small)%>
              <% end %>
              </div>
              <div class="user-case-details">
                <span class="fullname-user"><%= @project.user.profile.firmname %></span></br>
                <span class="user-service"><%= @project.user.profile.service %> </span>
                
                <%if @project.user.profile.reviews.blank? %>
                  <div hidden></div></br>
                <% else %>
                  <div class="average-review-rating" data-score="<%= @average_reviews %>" ></div>
                <% end %>

                <%= link_to 'MY PROFILE', {:action=>"show", :controller=>"profiles", :id=>@project.user.profile.id}, class: "btn btn-default btn-to-profile-in-show" %>
              </div>
            </div>

            <div class="project-divider"></div>

            <div class="project-details-fields">
              <h2 class="text-center project-description-show"> Project Details </h2></br>
              <div class="minimize description">
                <strong>Description: </strong>
                <% if @project.description.blank? %>
                  -
                <% else %>
                  <%= @project.description %>
                <% end %>
              </div>

              <div class="divider-project-details"></div>

              <div class="room-field-container">

              <% if user_signed_in? and current_user.id == @project.user.id %>
                <%= link_to 'EDIT PROJECT', edit_project_path(@project), :class => "btn btn-default btn-edit-project-show" %>
                <%= link_to 'TRASH PROJECT', @project, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-default btn-delete-project-show"%>
              <% end %>
              
                <div class="room-field">
                  <strong>Type of Project: </strong></br>
                  <%= @project.project_type %>
                </div>

                <div class="room-field">
                  <strong>Style: </strong></br>
                  <% if @project.style.blank? %>
                    -
                  <% else %>
                    <%= @project.style %>
                  <% end %>
                </div>

                <div class="room-field">
                  <strong>Location: </strong></br>
                  <%= @project.location %>
                </div>

                <div class="room-field">
                  <strong>Size: </strong></br>
                  <%= @project.size %>
                </div>

                <div class="room-field">
                  <strong>Year Finished: </strong></br>
                  <%= @project.year_finished %>
                </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<script>
var slick = $('.single-item').slick({
      arrows: true
    });

$(document).ready(slick)
$(document).on('page:load',slick)

$(document).ready(function() {
    // $("#lightGallery").lightGallery();
    $('.minimize').readmore({
      speed: 400,
      lessLink: '<a href="#" class="text-center">Close</a>',
      moreLink: '<a href="#" class="text-center">Read more</a>'
    });
    $('.average-review-rating').raty({
      readOnly: true,
      score: function(){
        return $(this).attr('data-score')
      },
      starHalf: 'fa fa-fw fa-star-half-o star-color',
      starOff: 'fa fa-fw fa-star-o star-color',
      starOn: 'fa fa-fw fa-star star-color'
    });
  }); 
</script>