config/routes.rb
Rails.application.routes.draw do

  resources :profiles, only: [:index, :edit, :show, :update] do
    resources :reviews
    resources :contacts, only: [:new, :create]
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

  devise_scope :user do
    get "professional/register" =>"registrations#professional_register"
    get "user/choose" => "registrations#choose"
  end

  resources :projects do
    # member do
    #   put "like" => "projects#upvote"
    # end
  end

  resources :project_attachments, only: [:edit, :update]

  #root 'projects#index'

  authenticated :user do
    root 'projects#index', as: :authenticated_root
  end

  root 'prehome#index'
  # get '*path' => redirect('/')

  #Additional Pages for sorting out projects and professional
    #Projects
    match 'commercials' => 'projects#commercials', :via => :get
    match 'residentials' => 'projects#residentials', :via => :get
    match 'offices' => 'projects#offices', :via => :get

    #Profile
    match 'professional/architects' => 'profiles#architects', :via => :get
    match 'professional/intdesigner' => 'profiles#interior_designers', :via => :get
    match 'professional/architect-firms' => 'profiles#architect_firms', :via => :get
    match 'professional/intdesigner-firms' => 'profiles#architect_firms', :via => :get
    match 'professional/design-firms' => 'profiles#design_firms', :via => :get
    match 'professional/land-architects' => 'profiles#land_architects', :via => :get
    match 'professional/gen-contractors' => 'profiles#gen_contractors', :via => :get
  
end

app/models/project_attachment.rb
class ProjectAttachment < ActiveRecord::Base

	  mount_uploader :picture, PictureUploader

		  # User Picture Validation
	  validates_integrity_of  :picture
	  validates_processing_of :picture

	  belongs_to :project

	  validates :picture, file_size: { less_than_or_equal_to: 8.megabytes }, presence: true, file_content_type: { allow: ['image/jpeg', 'image/png'] } 
end

app/controllers/project_attachments_controller.rb
class ProjectAttachmentsController < ApplicationController
  before_action :set_project_attachment, only: [:show, :edit, :update, :destroy]

  # GET /project_attachments/new
  def new
    @project_attachment = ProjectAttachment.new
  end

  # GET /project_attachments/1/edit
  def edit
  end

  # POST /project_attachments
  # POST /project_attachments.json
  def create
    @project_attachment = ProjectAttachment.new(project_attachment_params)

    respond_to do |format|
      if @project_attachment.save
        format.html { redirect_to @project_attachment, notice: 'Project attachment was successfully created.' }
        format.json { render :show, status: :created, location: @project_attachment }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /project_attachments/1
  # PATCH/PUT /project_attachments/1.json
  def update
    respond_to do |format|
      if @project_attachment.update(project_attachment_params)
        format.html { redirect_to @project_attachment.project, notice: 'Project attachment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /project_attachments/1
  # DELETE /project_attachments/1.json
  def destroy
    @project_attachment.destroy
    respond_to do |format|
      format.html { redirect_to project_attachments_url, notice: 'Project attachment was successfully destroyed.' }    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_attachment
      @project_attachment = ProjectAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_attachment_params
      params.require(:project_attachment).permit(:project_id, :picture)
    end
end

app/helpers/project_attachments_helper.rb
module ProjectAttachmentsHelper
end

app/views/project_attachments/_form.html.erb
<section class="form-section">
  <div class="form-container">
    <div class="form-page">
      <div class="auth-form">
        <%= image_tag @project_attachment.picture_url(:small) %>

      <%= form_for(@project_attachment) do |f| %>
          <% if @project_attachment.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@project_attachment.errors.count, "error") %> prohibited this project_attachment from being saved:</h2>

              <ul>
              <% @project_attachment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <h2>Update This Picture</h2></br>

           <div class="field">
             <label class="form-label">Replace Picture Of Your Projects: </label>
              <%= f.file_field :picture, accept: "image/png, image/jpg, image/jpeg", required: true %>
           </div>

          <div class="actions">
            <%= f.submit "UPDATE", class: "submit-action" %>
            <%= link_to "BACK", project_path(@project_attachment.project), class: "btn-form btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/project_attachments/edit.html.erb
<h1>Editing Project Attachment</h1>

<%= render 'form' %>

app/views/project_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Project Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_attachments.each do |project_attachment| %>
      <tr>
        <td><%= project_attachment.project_id %></td>
        <td><%= project_attachment.picture %></td>
        <td><%= link_to 'Show', project_attachment %></td>
        <td><%= link_to 'Edit', edit_project_attachment_path(project_attachment) %></td>
        <td><%= link_to 'Destroy', project_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project attachment', new_project_attachment_path %>

app/views/project_attachments/new.html.erb
<h1>New Project Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', project_attachments_path %>

app/views/project_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @project_attachment.project_id %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @project_attachment.picture %>
</p>

<%= link_to 'Edit', edit_project_attachment_path(@project_attachment) %> |
<%= link_to 'Back', project_attachments_path %>